### ISSUE TITLE
Create "NEW PAGE"

### ISSUE THREAD

**Issue by CaitlinBerger** [OSU-CS361-W17/group11_project2#1]
Create new page dialog, with instructions. Should include:

-  Instructions in HTML page as well as CSS styling giving instructions
-  JavaScript function to hide page when "begin" button is pressed

**Comment by RiverHendriksen** [comment]
I will work on this

**Comment by RiverHendriksen** [comment]
The intro page is made, since we made it a separate page we don't need to do anything fancy with hiding it via css
